version: "3.9"
services:
  web:
    build: .
    container_name: s2c-web
    ports:
      - "5000:5000"
    env_file: .env
    environment:
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
      REDIS_DB: "0"
    volumes:
      - ./secrets:/run/secrets:ro
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 15s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: s2c-redis
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}", "--save", "", "--appendonly", "no"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

volumes:
  redisdata:
